version: "3.9"
services:
  web:
    build:
      context: .
    container_name: db-server-app
    ports:
      - 8000:8000
    depends_on:
      - "db"
  db:
    image: "mysql:8.0.27"
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080